name: Predict with Models

on:
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn xgboost joblib

      - name: Run prediction script
        run: |
          python predict.py || (echo "Prediction script failed" && exit 1)

      - name: Commit and push predictions
        run: |
          git config --global user.name "chiragpalan"
          git config --global user.email "your-email@example.com"
          
          # Pull latest changes from the remote
          git pull origin main || echo "No changes to pull or already up-to-date"

          git add -A  # Add all new files
          git commit -m "Add predictions database" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
